// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
import { join } from "node:path";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// 1. Manually load the .env file just for this isolated Prisma CLI process
config({ path: join(process.cwd(), ".env") });

export default defineConfig({
	schema: "prisma/schema.prisma",
	migrations: {
		path: "prisma/migrations",
	},
	datasource: {
		url: process.env.AUTH_DATABASE_URL_TEST || process.env["AUTH_DATABASE_URL"],
	},
});
